version: '3.8'

services:
  cloud-flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-flask-app
    ports:
      - "5055:5055"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - FLASK_ENV=development
      - PORT=5055

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
