apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: LoadBalancer  # Use NodePort for external access
  ports:
  - port: 5055  # Expose Flask app on port 5055
    targetPort: 5055  # Target port for Flask app
    nodePort: 30007  # Custom NodePort (range: 30000-32767)
  selector:
    app: flask-app
