apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-rc
spec:
  replicas: 3
  selector:
    app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest  # Standard MongoDB Docker image
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
