# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
        - channel: '#kubernetes-alerts-adrian'
          send_resolved: true
          icon_url: https://avatars3.githubusercontent.com/u/3380462
